/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as authUpgradeImport } from './routes/(auth)/upgrade'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authSigninImport } from './routes/(auth)/signin'
import { Route as authGuestImport } from './routes/(auth)/guest'
import { Route as appGroupsImport } from './routes/(app)/groups'
import { Route as appInviteInviteIdImport } from './routes/(app)/invite/$inviteId'
import { Route as appGroupsGroupIdImport } from './routes/(app)/groups/$groupId'
import { Route as appGroupsGroupIdFoldersFolderIdImport } from './routes/(app)/groups/$groupId/folders/$folderId'
import { Route as appGroupsGroupIdChatsChatIdImport } from './routes/(app)/groups/$groupId/chats/$chatId'
import { Route as appGroupsGroupIdBoardsBoardIdImport } from './routes/(app)/groups/$groupId/boards/$boardId'

// Create Virtual Routes

const appGroupsIndexLazyImport = createFileRoute('/(app)/groups/')()
const appGroupsGroupIdIndexLazyImport = createFileRoute(
  '/(app)/groups/$groupId/',
)()
const appGroupsGroupIdAdminSettingsLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/settings',
)()
const appGroupsGroupIdAdminMembersLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/members',
)()
const appGroupsGroupIdAdminInvitesLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/invites',
)()
const appGroupsGroupIdAdminFoldersLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/folders',
)()
const appGroupsGroupIdAdminChatsLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/chats',
)()
const appGroupsGroupIdAdminCallsLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/calls',
)()
const appGroupsGroupIdAdminBoardsLazyImport = createFileRoute(
  '/(app)/groups/$groupId/admin/boards',
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authUpgradeRoute = authUpgradeImport
  .update({
    id: '/(auth)/upgrade',
    path: '/upgrade',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/upgrade.lazy').then((d) => d.Route))

const authSignupRoute = authSignupImport
  .update({
    id: '/(auth)/signup',
    path: '/signup',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/signup.lazy').then((d) => d.Route))

const authSigninRoute = authSigninImport
  .update({
    id: '/(auth)/signin',
    path: '/signin',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/signin.lazy').then((d) => d.Route))

const authGuestRoute = authGuestImport
  .update({
    id: '/(auth)/guest',
    path: '/guest',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/guest.lazy').then((d) => d.Route))

const appGroupsRoute = appGroupsImport
  .update({
    id: '/(app)/groups',
    path: '/groups',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/groups.lazy').then((d) => d.Route))

const appGroupsIndexLazyRoute = appGroupsIndexLazyImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => appGroupsRoute,
  } as any)
  .lazy(() => import('./routes/(app)/groups/index.lazy').then((d) => d.Route))

const appInviteInviteIdRoute = appInviteInviteIdImport
  .update({
    id: '/(app)/invite/$inviteId',
    path: '/invite/$inviteId',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/invite/$inviteId.lazy').then((d) => d.Route),
  )

const appGroupsGroupIdRoute = appGroupsGroupIdImport
  .update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => appGroupsRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/groups/$groupId.lazy').then((d) => d.Route),
  )

const appGroupsGroupIdIndexLazyRoute = appGroupsGroupIdIndexLazyImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => appGroupsGroupIdRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/groups/$groupId/index.lazy').then((d) => d.Route),
  )

const appGroupsGroupIdAdminSettingsLazyRoute =
  appGroupsGroupIdAdminSettingsLazyImport
    .update({
      id: '/admin/settings',
      path: '/admin/settings',
      getParentRoute: () => appGroupsGroupIdRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/groups/$groupId/admin/settings.lazy').then(
        (d) => d.Route,
      ),
    )

const appGroupsGroupIdAdminMembersLazyRoute =
  appGroupsGroupIdAdminMembersLazyImport
    .update({
      id: '/admin/members',
      path: '/admin/members',
      getParentRoute: () => appGroupsGroupIdRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/groups/$groupId/admin/members.lazy').then(
        (d) => d.Route,
      ),
    )

const appGroupsGroupIdAdminInvitesLazyRoute =
  appGroupsGroupIdAdminInvitesLazyImport
    .update({
      id: '/admin/invites',
      path: '/admin/invites',
      getParentRoute: () => appGroupsGroupIdRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/groups/$groupId/admin/invites.lazy').then(
        (d) => d.Route,
      ),
    )

const appGroupsGroupIdAdminFoldersLazyRoute =
  appGroupsGroupIdAdminFoldersLazyImport
    .update({
      id: '/admin/folders',
      path: '/admin/folders',
      getParentRoute: () => appGroupsGroupIdRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/groups/$groupId/admin/folders.lazy').then(
        (d) => d.Route,
      ),
    )

const appGroupsGroupIdAdminChatsLazyRoute = appGroupsGroupIdAdminChatsLazyImport
  .update({
    id: '/admin/chats',
    path: '/admin/chats',
    getParentRoute: () => appGroupsGroupIdRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/groups/$groupId/admin/chats.lazy').then(
      (d) => d.Route,
    ),
  )

const appGroupsGroupIdAdminCallsLazyRoute = appGroupsGroupIdAdminCallsLazyImport
  .update({
    id: '/admin/calls',
    path: '/admin/calls',
    getParentRoute: () => appGroupsGroupIdRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/groups/$groupId/admin/calls.lazy').then(
      (d) => d.Route,
    ),
  )

const appGroupsGroupIdAdminBoardsLazyRoute =
  appGroupsGroupIdAdminBoardsLazyImport
    .update({
      id: '/admin/boards',
      path: '/admin/boards',
      getParentRoute: () => appGroupsGroupIdRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/groups/$groupId/admin/boards.lazy').then(
        (d) => d.Route,
      ),
    )

const appGroupsGroupIdFoldersFolderIdRoute =
  appGroupsGroupIdFoldersFolderIdImport
    .update({
      id: '/folders/$folderId',
      path: '/folders/$folderId',
      getParentRoute: () => appGroupsGroupIdRoute,
    } as any)
    .lazy(() =>
      import('./routes/(app)/groups/$groupId/folders/$folderId.lazy').then(
        (d) => d.Route,
      ),
    )

const appGroupsGroupIdChatsChatIdRoute = appGroupsGroupIdChatsChatIdImport
  .update({
    id: '/chats/$chatId',
    path: '/chats/$chatId',
    getParentRoute: () => appGroupsGroupIdRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/groups/$groupId/chats/$chatId.lazy').then(
      (d) => d.Route,
    ),
  )

const appGroupsGroupIdBoardsBoardIdRoute = appGroupsGroupIdBoardsBoardIdImport
  .update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => appGroupsGroupIdRoute,
  } as any)
  .lazy(() =>
    import('./routes/(app)/groups/$groupId/boards/$boardId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/groups': {
      id: '/(app)/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof appGroupsImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/guest': {
      id: '/(auth)/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof authGuestImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/upgrade': {
      id: '/(auth)/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof authUpgradeImport
      parentRoute: typeof rootRoute
    }
    '/(app)/groups/$groupId': {
      id: '/(app)/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof appGroupsGroupIdImport
      parentRoute: typeof appGroupsImport
    }
    '/(app)/invite/$inviteId': {
      id: '/(app)/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof appInviteInviteIdImport
      parentRoute: typeof rootRoute
    }
    '/(app)/groups/': {
      id: '/(app)/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof appGroupsIndexLazyImport
      parentRoute: typeof appGroupsImport
    }
    '/(app)/groups/$groupId/': {
      id: '/(app)/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof appGroupsGroupIdIndexLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/boards/$boardId': {
      id: '/(app)/groups/$groupId/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/groups/$groupId/boards/$boardId'
      preLoaderRoute: typeof appGroupsGroupIdBoardsBoardIdImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/chats/$chatId': {
      id: '/(app)/groups/$groupId/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/groups/$groupId/chats/$chatId'
      preLoaderRoute: typeof appGroupsGroupIdChatsChatIdImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/folders/$folderId': {
      id: '/(app)/groups/$groupId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/groups/$groupId/folders/$folderId'
      preLoaderRoute: typeof appGroupsGroupIdFoldersFolderIdImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/boards': {
      id: '/(app)/groups/$groupId/admin/boards'
      path: '/admin/boards'
      fullPath: '/groups/$groupId/admin/boards'
      preLoaderRoute: typeof appGroupsGroupIdAdminBoardsLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/calls': {
      id: '/(app)/groups/$groupId/admin/calls'
      path: '/admin/calls'
      fullPath: '/groups/$groupId/admin/calls'
      preLoaderRoute: typeof appGroupsGroupIdAdminCallsLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/chats': {
      id: '/(app)/groups/$groupId/admin/chats'
      path: '/admin/chats'
      fullPath: '/groups/$groupId/admin/chats'
      preLoaderRoute: typeof appGroupsGroupIdAdminChatsLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/folders': {
      id: '/(app)/groups/$groupId/admin/folders'
      path: '/admin/folders'
      fullPath: '/groups/$groupId/admin/folders'
      preLoaderRoute: typeof appGroupsGroupIdAdminFoldersLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/invites': {
      id: '/(app)/groups/$groupId/admin/invites'
      path: '/admin/invites'
      fullPath: '/groups/$groupId/admin/invites'
      preLoaderRoute: typeof appGroupsGroupIdAdminInvitesLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/members': {
      id: '/(app)/groups/$groupId/admin/members'
      path: '/admin/members'
      fullPath: '/groups/$groupId/admin/members'
      preLoaderRoute: typeof appGroupsGroupIdAdminMembersLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
    '/(app)/groups/$groupId/admin/settings': {
      id: '/(app)/groups/$groupId/admin/settings'
      path: '/admin/settings'
      fullPath: '/groups/$groupId/admin/settings'
      preLoaderRoute: typeof appGroupsGroupIdAdminSettingsLazyImport
      parentRoute: typeof appGroupsGroupIdImport
    }
  }
}

// Create and export the route tree

interface appGroupsGroupIdRouteChildren {
  appGroupsGroupIdIndexLazyRoute: typeof appGroupsGroupIdIndexLazyRoute
  appGroupsGroupIdBoardsBoardIdRoute: typeof appGroupsGroupIdBoardsBoardIdRoute
  appGroupsGroupIdChatsChatIdRoute: typeof appGroupsGroupIdChatsChatIdRoute
  appGroupsGroupIdFoldersFolderIdRoute: typeof appGroupsGroupIdFoldersFolderIdRoute
  appGroupsGroupIdAdminBoardsLazyRoute: typeof appGroupsGroupIdAdminBoardsLazyRoute
  appGroupsGroupIdAdminCallsLazyRoute: typeof appGroupsGroupIdAdminCallsLazyRoute
  appGroupsGroupIdAdminChatsLazyRoute: typeof appGroupsGroupIdAdminChatsLazyRoute
  appGroupsGroupIdAdminFoldersLazyRoute: typeof appGroupsGroupIdAdminFoldersLazyRoute
  appGroupsGroupIdAdminInvitesLazyRoute: typeof appGroupsGroupIdAdminInvitesLazyRoute
  appGroupsGroupIdAdminMembersLazyRoute: typeof appGroupsGroupIdAdminMembersLazyRoute
  appGroupsGroupIdAdminSettingsLazyRoute: typeof appGroupsGroupIdAdminSettingsLazyRoute
}

const appGroupsGroupIdRouteChildren: appGroupsGroupIdRouteChildren = {
  appGroupsGroupIdIndexLazyRoute: appGroupsGroupIdIndexLazyRoute,
  appGroupsGroupIdBoardsBoardIdRoute: appGroupsGroupIdBoardsBoardIdRoute,
  appGroupsGroupIdChatsChatIdRoute: appGroupsGroupIdChatsChatIdRoute,
  appGroupsGroupIdFoldersFolderIdRoute: appGroupsGroupIdFoldersFolderIdRoute,
  appGroupsGroupIdAdminBoardsLazyRoute: appGroupsGroupIdAdminBoardsLazyRoute,
  appGroupsGroupIdAdminCallsLazyRoute: appGroupsGroupIdAdminCallsLazyRoute,
  appGroupsGroupIdAdminChatsLazyRoute: appGroupsGroupIdAdminChatsLazyRoute,
  appGroupsGroupIdAdminFoldersLazyRoute: appGroupsGroupIdAdminFoldersLazyRoute,
  appGroupsGroupIdAdminInvitesLazyRoute: appGroupsGroupIdAdminInvitesLazyRoute,
  appGroupsGroupIdAdminMembersLazyRoute: appGroupsGroupIdAdminMembersLazyRoute,
  appGroupsGroupIdAdminSettingsLazyRoute:
    appGroupsGroupIdAdminSettingsLazyRoute,
}

const appGroupsGroupIdRouteWithChildren =
  appGroupsGroupIdRoute._addFileChildren(appGroupsGroupIdRouteChildren)

interface appGroupsRouteChildren {
  appGroupsGroupIdRoute: typeof appGroupsGroupIdRouteWithChildren
  appGroupsIndexLazyRoute: typeof appGroupsIndexLazyRoute
}

const appGroupsRouteChildren: appGroupsRouteChildren = {
  appGroupsGroupIdRoute: appGroupsGroupIdRouteWithChildren,
  appGroupsIndexLazyRoute: appGroupsIndexLazyRoute,
}

const appGroupsRouteWithChildren = appGroupsRoute._addFileChildren(
  appGroupsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof appGroupsRouteWithChildren
  '/guest': typeof authGuestRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/upgrade': typeof authUpgradeRoute
  '/groups/$groupId': typeof appGroupsGroupIdRouteWithChildren
  '/invite/$inviteId': typeof appInviteInviteIdRoute
  '/groups/': typeof appGroupsIndexLazyRoute
  '/groups/$groupId/': typeof appGroupsGroupIdIndexLazyRoute
  '/groups/$groupId/boards/$boardId': typeof appGroupsGroupIdBoardsBoardIdRoute
  '/groups/$groupId/chats/$chatId': typeof appGroupsGroupIdChatsChatIdRoute
  '/groups/$groupId/folders/$folderId': typeof appGroupsGroupIdFoldersFolderIdRoute
  '/groups/$groupId/admin/boards': typeof appGroupsGroupIdAdminBoardsLazyRoute
  '/groups/$groupId/admin/calls': typeof appGroupsGroupIdAdminCallsLazyRoute
  '/groups/$groupId/admin/chats': typeof appGroupsGroupIdAdminChatsLazyRoute
  '/groups/$groupId/admin/folders': typeof appGroupsGroupIdAdminFoldersLazyRoute
  '/groups/$groupId/admin/invites': typeof appGroupsGroupIdAdminInvitesLazyRoute
  '/groups/$groupId/admin/members': typeof appGroupsGroupIdAdminMembersLazyRoute
  '/groups/$groupId/admin/settings': typeof appGroupsGroupIdAdminSettingsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest': typeof authGuestRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/upgrade': typeof authUpgradeRoute
  '/invite/$inviteId': typeof appInviteInviteIdRoute
  '/groups': typeof appGroupsIndexLazyRoute
  '/groups/$groupId': typeof appGroupsGroupIdIndexLazyRoute
  '/groups/$groupId/boards/$boardId': typeof appGroupsGroupIdBoardsBoardIdRoute
  '/groups/$groupId/chats/$chatId': typeof appGroupsGroupIdChatsChatIdRoute
  '/groups/$groupId/folders/$folderId': typeof appGroupsGroupIdFoldersFolderIdRoute
  '/groups/$groupId/admin/boards': typeof appGroupsGroupIdAdminBoardsLazyRoute
  '/groups/$groupId/admin/calls': typeof appGroupsGroupIdAdminCallsLazyRoute
  '/groups/$groupId/admin/chats': typeof appGroupsGroupIdAdminChatsLazyRoute
  '/groups/$groupId/admin/folders': typeof appGroupsGroupIdAdminFoldersLazyRoute
  '/groups/$groupId/admin/invites': typeof appGroupsGroupIdAdminInvitesLazyRoute
  '/groups/$groupId/admin/members': typeof appGroupsGroupIdAdminMembersLazyRoute
  '/groups/$groupId/admin/settings': typeof appGroupsGroupIdAdminSettingsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)/groups': typeof appGroupsRouteWithChildren
  '/(auth)/guest': typeof authGuestRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/upgrade': typeof authUpgradeRoute
  '/(app)/groups/$groupId': typeof appGroupsGroupIdRouteWithChildren
  '/(app)/invite/$inviteId': typeof appInviteInviteIdRoute
  '/(app)/groups/': typeof appGroupsIndexLazyRoute
  '/(app)/groups/$groupId/': typeof appGroupsGroupIdIndexLazyRoute
  '/(app)/groups/$groupId/boards/$boardId': typeof appGroupsGroupIdBoardsBoardIdRoute
  '/(app)/groups/$groupId/chats/$chatId': typeof appGroupsGroupIdChatsChatIdRoute
  '/(app)/groups/$groupId/folders/$folderId': typeof appGroupsGroupIdFoldersFolderIdRoute
  '/(app)/groups/$groupId/admin/boards': typeof appGroupsGroupIdAdminBoardsLazyRoute
  '/(app)/groups/$groupId/admin/calls': typeof appGroupsGroupIdAdminCallsLazyRoute
  '/(app)/groups/$groupId/admin/chats': typeof appGroupsGroupIdAdminChatsLazyRoute
  '/(app)/groups/$groupId/admin/folders': typeof appGroupsGroupIdAdminFoldersLazyRoute
  '/(app)/groups/$groupId/admin/invites': typeof appGroupsGroupIdAdminInvitesLazyRoute
  '/(app)/groups/$groupId/admin/members': typeof appGroupsGroupIdAdminMembersLazyRoute
  '/(app)/groups/$groupId/admin/settings': typeof appGroupsGroupIdAdminSettingsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/guest'
    | '/signin'
    | '/signup'
    | '/upgrade'
    | '/groups/$groupId'
    | '/invite/$inviteId'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/boards/$boardId'
    | '/groups/$groupId/chats/$chatId'
    | '/groups/$groupId/folders/$folderId'
    | '/groups/$groupId/admin/boards'
    | '/groups/$groupId/admin/calls'
    | '/groups/$groupId/admin/chats'
    | '/groups/$groupId/admin/folders'
    | '/groups/$groupId/admin/invites'
    | '/groups/$groupId/admin/members'
    | '/groups/$groupId/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guest'
    | '/signin'
    | '/signup'
    | '/upgrade'
    | '/invite/$inviteId'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/boards/$boardId'
    | '/groups/$groupId/chats/$chatId'
    | '/groups/$groupId/folders/$folderId'
    | '/groups/$groupId/admin/boards'
    | '/groups/$groupId/admin/calls'
    | '/groups/$groupId/admin/chats'
    | '/groups/$groupId/admin/folders'
    | '/groups/$groupId/admin/invites'
    | '/groups/$groupId/admin/members'
    | '/groups/$groupId/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/(app)/groups'
    | '/(auth)/guest'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/upgrade'
    | '/(app)/groups/$groupId'
    | '/(app)/invite/$inviteId'
    | '/(app)/groups/'
    | '/(app)/groups/$groupId/'
    | '/(app)/groups/$groupId/boards/$boardId'
    | '/(app)/groups/$groupId/chats/$chatId'
    | '/(app)/groups/$groupId/folders/$folderId'
    | '/(app)/groups/$groupId/admin/boards'
    | '/(app)/groups/$groupId/admin/calls'
    | '/(app)/groups/$groupId/admin/chats'
    | '/(app)/groups/$groupId/admin/folders'
    | '/(app)/groups/$groupId/admin/invites'
    | '/(app)/groups/$groupId/admin/members'
    | '/(app)/groups/$groupId/admin/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appGroupsRoute: typeof appGroupsRouteWithChildren
  authGuestRoute: typeof authGuestRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authUpgradeRoute: typeof authUpgradeRoute
  appInviteInviteIdRoute: typeof appInviteInviteIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appGroupsRoute: appGroupsRouteWithChildren,
  authGuestRoute: authGuestRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authUpgradeRoute: authUpgradeRoute,
  appInviteInviteIdRoute: appInviteInviteIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/groups",
        "/(auth)/guest",
        "/(auth)/signin",
        "/(auth)/signup",
        "/(auth)/upgrade",
        "/(app)/invite/$inviteId"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/(app)/groups": {
      "filePath": "(app)/groups.ts",
      "children": [
        "/(app)/groups/$groupId",
        "/(app)/groups/"
      ]
    },
    "/(auth)/guest": {
      "filePath": "(auth)/guest.ts"
    },
    "/(auth)/signin": {
      "filePath": "(auth)/signin.ts"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.ts"
    },
    "/(auth)/upgrade": {
      "filePath": "(auth)/upgrade.ts"
    },
    "/(app)/groups/$groupId": {
      "filePath": "(app)/groups/$groupId.ts",
      "parent": "/(app)/groups",
      "children": [
        "/(app)/groups/$groupId/",
        "/(app)/groups/$groupId/boards/$boardId",
        "/(app)/groups/$groupId/chats/$chatId",
        "/(app)/groups/$groupId/folders/$folderId",
        "/(app)/groups/$groupId/admin/boards",
        "/(app)/groups/$groupId/admin/calls",
        "/(app)/groups/$groupId/admin/chats",
        "/(app)/groups/$groupId/admin/folders",
        "/(app)/groups/$groupId/admin/invites",
        "/(app)/groups/$groupId/admin/members",
        "/(app)/groups/$groupId/admin/settings"
      ]
    },
    "/(app)/invite/$inviteId": {
      "filePath": "(app)/invite/$inviteId.ts"
    },
    "/(app)/groups/": {
      "filePath": "(app)/groups/index.lazy.tsx",
      "parent": "/(app)/groups"
    },
    "/(app)/groups/$groupId/": {
      "filePath": "(app)/groups/$groupId/index.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/boards/$boardId": {
      "filePath": "(app)/groups/$groupId/boards/$boardId.ts",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/chats/$chatId": {
      "filePath": "(app)/groups/$groupId/chats/$chatId.ts",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/folders/$folderId": {
      "filePath": "(app)/groups/$groupId/folders/$folderId.ts",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/boards": {
      "filePath": "(app)/groups/$groupId/admin/boards.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/calls": {
      "filePath": "(app)/groups/$groupId/admin/calls.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/chats": {
      "filePath": "(app)/groups/$groupId/admin/chats.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/folders": {
      "filePath": "(app)/groups/$groupId/admin/folders.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/invites": {
      "filePath": "(app)/groups/$groupId/admin/invites.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/members": {
      "filePath": "(app)/groups/$groupId/admin/members.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    },
    "/(app)/groups/$groupId/admin/settings": {
      "filePath": "(app)/groups/$groupId/admin/settings.lazy.tsx",
      "parent": "/(app)/groups/$groupId"
    }
  }
}
ROUTE_MANIFEST_END */
