/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as GroupsImport } from './routes/groups'
import { Route as GroupsGroupIdImport } from './routes/groups/$groupId'
import { Route as GroupsGroupIdFoldersFolderIdImport } from './routes/groups/$groupId/folders/$folderId'
import { Route as GroupsGroupIdChatsChatIdImport } from './routes/groups/$groupId/chats/$chatId'
import { Route as GroupsGroupIdAdminMembersImport } from './routes/groups/$groupId/admin/members'
import { Route as GroupsGroupIdAdminInvitesImport } from './routes/groups/$groupId/admin/invites'

// Create Virtual Routes

const GroupsIndexLazyImport = createFileRoute('/groups/')()
const GroupsGroupIdIndexLazyImport = createFileRoute('/groups/$groupId/')()
const GroupsGroupIdAdminSettingsLazyImport = createFileRoute(
  '/groups/$groupId/admin/settings',
)()
const GroupsGroupIdAdminFoldersLazyImport = createFileRoute(
  '/groups/$groupId/admin/folders',
)()
const GroupsGroupIdAdminChatsLazyImport = createFileRoute(
  '/groups/$groupId/admin/chats',
)()

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const GroupsRoute = GroupsImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/groups.lazy').then((d) => d.Route))

const GroupsIndexLazyRoute = GroupsIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any).lazy(() => import('./routes/groups/index.lazy').then((d) => d.Route))

const GroupsGroupIdRoute = GroupsGroupIdImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId.lazy').then((d) => d.Route),
)

const GroupsGroupIdIndexLazyRoute = GroupsGroupIdIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/index.lazy').then((d) => d.Route),
)

const GroupsGroupIdAdminSettingsLazyRoute =
  GroupsGroupIdAdminSettingsLazyImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/admin/settings.lazy').then((d) => d.Route),
  )

const GroupsGroupIdAdminFoldersLazyRoute =
  GroupsGroupIdAdminFoldersLazyImport.update({
    id: '/admin/folders',
    path: '/admin/folders',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/admin/folders.lazy').then((d) => d.Route),
  )

const GroupsGroupIdAdminChatsLazyRoute =
  GroupsGroupIdAdminChatsLazyImport.update({
    id: '/admin/chats',
    path: '/admin/chats',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/admin/chats.lazy').then((d) => d.Route),
  )

const GroupsGroupIdFoldersFolderIdRoute =
  GroupsGroupIdFoldersFolderIdImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/folders/$folderId.lazy').then(
      (d) => d.Route,
    ),
  )

const GroupsGroupIdChatsChatIdRoute = GroupsGroupIdChatsChatIdImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => GroupsGroupIdRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/chats/$chatId.lazy').then((d) => d.Route),
)

const GroupsGroupIdAdminMembersRoute = GroupsGroupIdAdminMembersImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => GroupsGroupIdRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/admin/members.lazy').then((d) => d.Route),
)

const GroupsGroupIdAdminInvitesRoute = GroupsGroupIdAdminInvitesImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => GroupsGroupIdRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/admin/invites.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdImport
      parentRoute: typeof GroupsImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexLazyImport
      parentRoute: typeof GroupsImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexLazyImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/admin/invites': {
      id: '/groups/$groupId/admin/invites'
      path: '/admin/invites'
      fullPath: '/groups/$groupId/admin/invites'
      preLoaderRoute: typeof GroupsGroupIdAdminInvitesImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/admin/members': {
      id: '/groups/$groupId/admin/members'
      path: '/admin/members'
      fullPath: '/groups/$groupId/admin/members'
      preLoaderRoute: typeof GroupsGroupIdAdminMembersImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/chats/$chatId': {
      id: '/groups/$groupId/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/groups/$groupId/chats/$chatId'
      preLoaderRoute: typeof GroupsGroupIdChatsChatIdImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/folders/$folderId': {
      id: '/groups/$groupId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/groups/$groupId/folders/$folderId'
      preLoaderRoute: typeof GroupsGroupIdFoldersFolderIdImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/admin/chats': {
      id: '/groups/$groupId/admin/chats'
      path: '/admin/chats'
      fullPath: '/groups/$groupId/admin/chats'
      preLoaderRoute: typeof GroupsGroupIdAdminChatsLazyImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/admin/folders': {
      id: '/groups/$groupId/admin/folders'
      path: '/admin/folders'
      fullPath: '/groups/$groupId/admin/folders'
      preLoaderRoute: typeof GroupsGroupIdAdminFoldersLazyImport
      parentRoute: typeof GroupsGroupIdImport
    }
    '/groups/$groupId/admin/settings': {
      id: '/groups/$groupId/admin/settings'
      path: '/admin/settings'
      fullPath: '/groups/$groupId/admin/settings'
      preLoaderRoute: typeof GroupsGroupIdAdminSettingsLazyImport
      parentRoute: typeof GroupsGroupIdImport
    }
  }
}

// Create and export the route tree

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdIndexLazyRoute: typeof GroupsGroupIdIndexLazyRoute
  GroupsGroupIdAdminInvitesRoute: typeof GroupsGroupIdAdminInvitesRoute
  GroupsGroupIdAdminMembersRoute: typeof GroupsGroupIdAdminMembersRoute
  GroupsGroupIdChatsChatIdRoute: typeof GroupsGroupIdChatsChatIdRoute
  GroupsGroupIdFoldersFolderIdRoute: typeof GroupsGroupIdFoldersFolderIdRoute
  GroupsGroupIdAdminChatsLazyRoute: typeof GroupsGroupIdAdminChatsLazyRoute
  GroupsGroupIdAdminFoldersLazyRoute: typeof GroupsGroupIdAdminFoldersLazyRoute
  GroupsGroupIdAdminSettingsLazyRoute: typeof GroupsGroupIdAdminSettingsLazyRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdIndexLazyRoute: GroupsGroupIdIndexLazyRoute,
  GroupsGroupIdAdminInvitesRoute: GroupsGroupIdAdminInvitesRoute,
  GroupsGroupIdAdminMembersRoute: GroupsGroupIdAdminMembersRoute,
  GroupsGroupIdChatsChatIdRoute: GroupsGroupIdChatsChatIdRoute,
  GroupsGroupIdFoldersFolderIdRoute: GroupsGroupIdFoldersFolderIdRoute,
  GroupsGroupIdAdminChatsLazyRoute: GroupsGroupIdAdminChatsLazyRoute,
  GroupsGroupIdAdminFoldersLazyRoute: GroupsGroupIdAdminFoldersLazyRoute,
  GroupsGroupIdAdminSettingsLazyRoute: GroupsGroupIdAdminSettingsLazyRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsIndexLazyRoute: typeof GroupsIndexLazyRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsIndexLazyRoute: GroupsIndexLazyRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

export interface FileRoutesByFullPath {
  '/groups': typeof GroupsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/': typeof GroupsIndexLazyRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexLazyRoute
  '/groups/$groupId/admin/invites': typeof GroupsGroupIdAdminInvitesRoute
  '/groups/$groupId/admin/members': typeof GroupsGroupIdAdminMembersRoute
  '/groups/$groupId/chats/$chatId': typeof GroupsGroupIdChatsChatIdRoute
  '/groups/$groupId/folders/$folderId': typeof GroupsGroupIdFoldersFolderIdRoute
  '/groups/$groupId/admin/chats': typeof GroupsGroupIdAdminChatsLazyRoute
  '/groups/$groupId/admin/folders': typeof GroupsGroupIdAdminFoldersLazyRoute
  '/groups/$groupId/admin/settings': typeof GroupsGroupIdAdminSettingsLazyRoute
}

export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/groups': typeof GroupsIndexLazyRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexLazyRoute
  '/groups/$groupId/admin/invites': typeof GroupsGroupIdAdminInvitesRoute
  '/groups/$groupId/admin/members': typeof GroupsGroupIdAdminMembersRoute
  '/groups/$groupId/chats/$chatId': typeof GroupsGroupIdChatsChatIdRoute
  '/groups/$groupId/folders/$folderId': typeof GroupsGroupIdFoldersFolderIdRoute
  '/groups/$groupId/admin/chats': typeof GroupsGroupIdAdminChatsLazyRoute
  '/groups/$groupId/admin/folders': typeof GroupsGroupIdAdminFoldersLazyRoute
  '/groups/$groupId/admin/settings': typeof GroupsGroupIdAdminSettingsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/groups': typeof GroupsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/': typeof GroupsIndexLazyRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexLazyRoute
  '/groups/$groupId/admin/invites': typeof GroupsGroupIdAdminInvitesRoute
  '/groups/$groupId/admin/members': typeof GroupsGroupIdAdminMembersRoute
  '/groups/$groupId/chats/$chatId': typeof GroupsGroupIdChatsChatIdRoute
  '/groups/$groupId/folders/$folderId': typeof GroupsGroupIdFoldersFolderIdRoute
  '/groups/$groupId/admin/chats': typeof GroupsGroupIdAdminChatsLazyRoute
  '/groups/$groupId/admin/folders': typeof GroupsGroupIdAdminFoldersLazyRoute
  '/groups/$groupId/admin/settings': typeof GroupsGroupIdAdminSettingsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/groups'
    | '/signin'
    | '/signup'
    | '/groups/$groupId'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/admin/invites'
    | '/groups/$groupId/admin/members'
    | '/groups/$groupId/chats/$chatId'
    | '/groups/$groupId/folders/$folderId'
    | '/groups/$groupId/admin/chats'
    | '/groups/$groupId/admin/folders'
    | '/groups/$groupId/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/admin/invites'
    | '/groups/$groupId/admin/members'
    | '/groups/$groupId/chats/$chatId'
    | '/groups/$groupId/folders/$folderId'
    | '/groups/$groupId/admin/chats'
    | '/groups/$groupId/admin/folders'
    | '/groups/$groupId/admin/settings'
  id:
    | '__root__'
    | '/groups'
    | '/signin'
    | '/signup'
    | '/groups/$groupId'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/admin/invites'
    | '/groups/$groupId/admin/members'
    | '/groups/$groupId/chats/$chatId'
    | '/groups/$groupId/folders/$folderId'
    | '/groups/$groupId/admin/chats'
    | '/groups/$groupId/admin/folders'
    | '/groups/$groupId/admin/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  GroupsRoute: typeof GroupsRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  GroupsRoute: GroupsRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/groups",
        "/signin",
        "/signup"
      ]
    },
    "/groups": {
      "filePath": "groups.ts",
      "children": [
        "/groups/$groupId",
        "/groups/"
      ]
    },
    "/signin": {
      "filePath": "signin.ts"
    },
    "/signup": {
      "filePath": "signup.ts"
    },
    "/groups/$groupId": {
      "filePath": "groups/$groupId.ts",
      "parent": "/groups",
      "children": [
        "/groups/$groupId/",
        "/groups/$groupId/admin/invites",
        "/groups/$groupId/admin/members",
        "/groups/$groupId/chats/$chatId",
        "/groups/$groupId/folders/$folderId",
        "/groups/$groupId/admin/chats",
        "/groups/$groupId/admin/folders",
        "/groups/$groupId/admin/settings"
      ]
    },
    "/groups/": {
      "filePath": "groups/index.lazy.tsx",
      "parent": "/groups"
    },
    "/groups/$groupId/": {
      "filePath": "groups/$groupId/index.lazy.tsx",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/admin/invites": {
      "filePath": "groups/$groupId/admin/invites.ts",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/admin/members": {
      "filePath": "groups/$groupId/admin/members.ts",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/chats/$chatId": {
      "filePath": "groups/$groupId/chats/$chatId.ts",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/folders/$folderId": {
      "filePath": "groups/$groupId/folders/$folderId.ts",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/admin/chats": {
      "filePath": "groups/$groupId/admin/chats.lazy.tsx",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/admin/folders": {
      "filePath": "groups/$groupId/admin/folders.lazy.tsx",
      "parent": "/groups/$groupId"
    },
    "/groups/$groupId/admin/settings": {
      "filePath": "groups/$groupId/admin/settings.lazy.tsx",
      "parent": "/groups/$groupId"
    }
  }
}
ROUTE_MANIFEST_END */
